version: '3.8'

services:
  fastapi-yolo:
    image: fastapi-yolo-gpu:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./:/app
